Update deploy.yml
change
uses: actions/setup-ruby@v1
to
uses: ruby/setup-ruby@v1

due to error:
Run actions/setup-ruby@v1
  with:
    ruby-version: 2.7
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.7 not found